export function userChooseRock() {
  const DEFAULT_IMG = document.querySelector(".default-img");

  if (DEFAULT_IMG.dataset.chosen !== "true") {
    DEFAULT_IMG.src = "src/assets/rock.jpeg";
    DEFAULT_IMG.dataset.chosen = "true";
  }

  // generate a random image

  // generate a random image

  // if user selected image is equal to the random image
  // generated by the computer, then results is draw.

  // otherwise if the user selected image is paper and the
  // the computer selected random image is rock, then user wins

  // otherwise if the user selected image is rock and the computer
  // selected random image is paper, then computer wins

  // otherwise if the user selected image is paper and the computer
  // selected image is scissors, then computer wins

  // otherwise if the user selected image is scissors and the computer
  // selected random image is paper, user wins

  // otherwise if the user selected image is scissors and the
  // computer selected random image is rock, then computer
  // wins

  // otherwise if the user selected image is rock and the
  // computer selected random image is scissors, then user
  // wins
}
